version: '3'

services:
  myapp:
    container_name: powerflex-ts-docker-mongo
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.dev
      args:
        - PORT = ${PORT}
    environment:
      MONGO_URI: 'mongodb://mongo:27017/myapp'
      PORT: '3001'
    ports:
      - 3001:${PORT}
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - ./:/usr/local/apps/myapp/dev
      - ignore:/usr/local/apps/myapp/dev/node_modules/
  mongo:
    image: 'mongo'
    ports:
      - '27017:27017'
    volumes:
      - 'mongo-data:/data/db'
volumes:
  mongo-data:
  ignore:
